### PR TITLE
fix for 3pl model

### PR DESCRIPTION
**Pull request by charchit7**

### CODE REVIEW

**Comment by jplalor** [comment]
Instead of adding the check to cli.py, I think it makes more sense to remove priors as an argument for the 3pl model (similar to the 4pl model). Can you make that change?

**Comment by charchit7** [comment]
Sure, John, I thought it was being used by someone.

**Comment by jplalor** [comment]
Thanks! Last step is to update the tests to remove TestThreePL.test_priors

**Comment by charchit7** [comment]
Sure, done John!

**Comment by jplalor** [comment]
Thanks!

**Comment by charchit7** [comment]
Thanks John!

**Pull request merged**
