### PR TITLE
Torch version

### PR DESCRIPTION
**Pull request by nihalnayak**
Updated the torch version in `pyproject.toml`. This should make the package compatible with more recent packages.

### CODE REVIEW

**Comment by jplalor** [comment]
See https://github.com/nd-ball/py-irt/pull/76 for the fix that implements the same as this PR. Thanks!

**Comment by nihalnayak** [comment]
@jplalor Thanks for the fix. This PR is slightly different from #76. Is there any reason why the torch version is `torch==2.2.0` instead of `torch==^2.2.0`?

**Comment by jplalor** [comment]
You're right. Can you resolve the merge conflicts on your branch and push, then I can merge to the master?

**Comment by nihalnayak** [comment]
I've resolved the merge conflicts. Let me know if this is okay.

**Comment by jplalor** [comment]
Thanks!

**Pull request merged**
